name: kids360_kids
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  device_apps: ^2.2.0
  get: ^4.6.6
  usage_stats: ^1.2.0
  intl: ^0.19.0
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  get_storage: ^2.1.1
  location: 
    path: "./location-5.0.3"
  http: ^1.2.0
  html: ^0.15.4
  cached_network_image: ^3.3.1
  firebase_messaging: ^14.9.4
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.1+2
  alarm: ^3.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  image_path: "assets/png/kid360 kid.png"

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

  fonts:
    - family: Lora-Regular
      fonts:
        - asset: assets/fonts/nunitoregular.ttf